### ISSUE TITLE
Mob Catcher Issue

### ISSUE THREAD

**Issue by mckay77** [christianbutnot/freedomofprogression#5]
**What modpack/mod?**
Mob Catcher

**Describe the bug**
This is more of an FYI for you and anyone who uses this pack/mod.  I understand this is not your mod and therefor not your issue to fix.  However, I thought you should be aware so the mod can be removed or updated.

On a server (Not LAN)...  When having the Mob Capture Device Launcher in your inventory and then falling into the water, you are put in a disconnect loop.  It took a moderator TP-ing me out to their dryland location to end the loop.

**To Reproduce**
1. Place Mob Launcher in inventory
2. Fall or walk into the water
3. Disconnect loop

**Expected behavior**
Expect not to DC.

**Crash Reports & Latest logs**
Because I don't have access to the server backend, I can not provide any error logs.  The only error message received on the player side is the generic disconnected from the server message.

**Comment by christianbutnot** [comment]
Will update the mod when I have time and hope that it fixes it. If not, I'll see about removing it and replacing it with something similar. 

Is the server running on plain forge, or a modified version (such as one that allows plugins & mods together)?
